language: julia
sudo: true

os:
    - linux
    - osx
    - windows

addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0

julia:
    - 1.0
    - 1.3
    - nightly

matrix:
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      julia: 1.0
    - os: windows
      julia: 1.0

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - travis_wait 30 $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
    - julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
